# coding:utf-8
#登录使用的微博
weiboID:
    - username: '15678264837'
      password: 'poiu11292'
    - username: '15577724762'
      password: 'poiu11292'
    - username: '15678075354'
      password: 'poiu11292'
    - username: '15678265034'
      password: 'poiu11292'
    - username: '18404477785'
      password: 'poiu11292'
#关键字
keywords:
  - word: '绝地求生+XDD'
  - word: '绝地求生+呆妹儿'
  - word: '焦虑'
  - word: '抑郁+亢奋'
#  - word: '王俊凯'
#  - word: 'TFBOYS+易烊千玺'
#  - word: '海洛因'

#  - word: '冰毒'

#目标微博ID
targetID:
  - userid: '1575168515'
#  - userid: '2873725572'
#  - userid: '1038561943'

#翻页上限：
maxPageForTweets: 10000
maxPageForComments: 10000

#当enable为True时，仅爬取date值之前的信息。
beforeDate:
  enable: False
  date: '2018-04-22 00:00'

#redis配置信息
redis:
  host: 127.0.0.1
  port: 6379

#MongoDB配置信息
mongodb:
    MONGO_URI: 'mongodb://czk:czk10101@127.0.0.1/test'
    MONGO_DATABASE: 'test'
