# coding:utf-8
weiboIDForTweets:
    - username: '15678264837'
      password: 'poiu11292'
#    - username: '15577724762'
#      password: 'poiu11292'
#    - username: '15678075354'
#      password: 'poiu11292'


weiboIDForComments:
    - username: '15678265034'
      password: 'poiu11292'

weiboIDForUserSearch:
    - username: '18404477785'
      password: 'poiu11292'


keywords:
#  - word: '绝地求生+XDD'
#  - word: '绝地求生+呆妹儿'
#  - word: '王俊凯'
#  - word: 'TFBOYS+易烊千玺'
#  - word: '海洛因'
  - word: '抑郁+亢奋'
#  - word: '冰毒'
  - word: '焦虑'

targetID:
#  - userid: '2873725572'
#  - userid: '1038561943'
  - userid: '1575168515'

#翻页上限：
maxPageForTweets: 10000

maxPageForComments: 10000

beforeDate:
  enable: False
  date: '2018-04-22 00:00'

redis:
  host: 127.0.0.1
  port: 6379



mongodb:
    MONGO_URI: 'mongodb://czk:czk10101@127.0.0.1/test'
    MONGO_DATABASE: 'test'


# warning by email
email:
    # your email must open smtp & pop3 service
    server: smtp.sina.com
    port: 587
    from: xxxxx@sina.com         #sendingemailaccount
    password: xxxx               #youremailpasswd
    to: xxxxxxxx@139.com         #bind 139 email,so your phone will receive the warning message
    subject: Warning Of Weibo Spider
    warning_info: Please find out the reason why the spider stops working