# coding:utf-8
weiboIDForTweets:
    - username: '15678264837'
      password: poiu11292
#    - username: 15577724762
#      password: poiu11292
#    - username: 15678075354
#      password: poiu11292
#

weiboIDForComments:
    - username: 15678265034
      password: poiu11292

weiboIDForUserSearch:
    - username: 18404477785
      password: poiu11292


keywords:
  - word: '绝地求生+XDD'
  - word: '绝地求生+呆妹儿'

#翻页上限：
max_page_for_tweets:

max_page_for_comments:

userid:

username:


redis:
  host: 127.0.0.1
  port: 6379



mongodb:
    host: 127.0.0.1
    port: 27017
    user:
    password:
    db_name:
    db_type:

# warning by email
email:
    # your email must open smtp & pop3 service
    server: smtp.sina.com
    port: 587
    from: xxxxx@sina.com         #sendingemailaccount
    password: xxxx               #youremailpasswd
    to: xxxxxxxx@139.com         #bind 139 email,so your phone will receive the warning message
    subject: Warning Of Weibo Spider
    warning_info: Please find out the reason why the spider stops working