# coding:utf-8
mongodb:
    host: 127.0.0.1
    port: 27017
    user:
    password:
    db_name:
    db_type:

# warning by email
email:
    # your email must open smtp & pop3 service
    server: smtp.sina.com
    port: 587
    from: xxxxx@sina.com         #sendingemailaccount
    password: xxxx               #youremailpasswd
    to: xxxxxxxx@139.com         #bind 139 email,so your phone will receive the warning message
    subject: Warning Of Weibo Spider
    warning_info: Please find out the reason why the spider stops working