FROM python:3.6

ENV PATH /usr/local/bin:$PATH
ENV LANG en_US.UTF-8

RUN apt-get update -y \
    && apt-get dist-upgrade -y \
    && apt-get install -y gettext vim tree curl net-tools iputils-ping dstat htop ipython3 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /build/
COPY requirements.txt /build/
RUN pip install -r /build/requirements.txt

WORKDIR /work

CMD ["bash"]